sudo: required

language: go

go:
  - 1.9.x
  
install:
  - echo "Please don't go get"

services:
  - docker

before_script:
- bash contrib/set_travis_experimental_mode.sh
- curl -sSL get.docker.com | sudo -E sh

after_success:
    - if [ ! -z "$TRAVIS_TAG" ] ; then 
        docker tag $DOCKER_NS/faas-netesd:latest $DOCKER_NS/faas-netesd:$TRAVIS_TAG;
        echo $DOCKER_PASSWORD | docker login -u=$DOCKER_USERNAME --password-stdin;
        docker push $DOCKER_NS/faas-netesd:$TRAVIS_TAG;
        fi

script:
  - make build
